# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Loja de Temas Tray
title: Documentação - Loja de Temas Tray
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Documentação oficial da Loja de Temas da Tray E-commerce, tire aqui todas as suas dúvidas
baseurl: "/documentacao-temas" # the subpath of your site, e.g. /blog
url: "https://tray-tecnologia.github.io/documentacao-temas/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  style: compressed
  
timezone: America/Sao_Paulo