# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Documentação - Loja de Temas
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Documentação da loja de temas da Tray E-commerce
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://documentacao-temas-ezanattatray.c9users.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  style: compressed
  
timezone: America/Sao_Paulo